---
title: "&#32;"
output:
  html_document:
    css: "styles.css"
    theme: "lumen"
    df_print: paged
---

```{r setup, include=FALSE}
# Environment set up
knitr::opts_chunk$set(echo=FALSE)

library(DT)
library(tidyr)
library(dplyr)
library(here)
library(fontawesome)

screening_data <- read.csv(here("Data", "screening_data.csv"))
patient_data <- read.csv(here("Data", "patient_data.csv"))

# no STARS Day Hospital in this list...
screening_data <- screening_data %>% mutate(screen_hospital = ifelse(screen_hospital == 1, "Royal Brisbane and Women's Hospital", ifelse(screen_hospital == 2, "Surgical, Treatment and Rehabilitation Service", ifelse(screen_hospital ==3, "Brighton Rehabilitation Unit", ifelse(screen_hospital == 4, "Caboolture Hospital", ifelse(screen_hospital ==5, "Redcliffe Hospital", ifelse(screen_hospital==6, "St Vincent's Hospital Melbourne - Acute Fitzroy", ifelse(screen_hospital==7, "St Vincent's Hospital Melbourne - Rehab Fitzroy", ifelse(screen_hospital ==8, "St Vincent's Hospital Melbourne - Rehab SGHS", ifelse(screen_hospital==9, "Monash Medical Centre", ifelse(screen_hospital==10, "Kingston Centre", ifelse(screen_hospital ==11, "Sir Charles Gairdner Hospital", ifelse(screen_hospital==12, "Osborne Park Hospital", ifelse(screen_hospital ==13, "Fiona Stanley Hospital",ifelse(screen_hospital==14, "Fremantle Hospital",ifelse(screen_hospital==15, "Casey Hospital",ifelse(screen_hospital==16, "SVHM - Rehab@Home", NA)))))))))))))))))

patient_data <- patient_data %>% mutate(admhospital = ifelse(admhospital == 1, "Royal Brisbane and Women's Hospital", ifelse(admhospital == 2, "Surgical, Treatment and Rehabilitation Service", ifelse(admhospital == 3, "Brighton Rehabilitation Unit", ifelse(admhospital == 4, "Caboolture Hospital", ifelse(admhospital == 5, "Redcliffe Hospital", ifelse(admhospital == 6, "St Vincent's Hospital Melbourne - Acute", ifelse(admhospital == 7, "St Vincent's Hospital Melbourne - Rehab Fitzroy", ifelse(admhospital == 8, "St Vincent's Hospital Melbourne - Rehab SGHS", ifelse(admhospital == 9, "Monash Medical Centre", ifelse(admhospital == 10, "Kingston Centre", ifelse(admhospital == 11, "Sir Charles Gairdner Hospital", ifelse(admhospital == 12, "Osborne Park Hospital", ifelse(admhospital == 13, "Fiona Stanley Hospital",ifelse(admhospital == 14, "Fremantle Hospital",ifelse(admhospital == 15, "STARS Day Hospital",ifelse(admhospital == 16, "Casey Hospital",ifelse(admhospital == 17, "SVHM - Rehab@Home", NA)))))))))))))))))) %>% mutate(redcap_event_name = ifelse(redcap_event_name == "inpatient_acute_arm_1","Acute",ifelse(redcap_event_name == "inpatient_rehabsub_arm_1","Rehab","Community"))) %>% filter(grepl('-',participant_id))

```

<div style="text-align:right; font-size: 12px; color: gray;">
  Report generated on `r format(Sys.Date(), "%d %B %Y")`
</div>

```{r}
clinicians <- patient_data %>%select("participant_id","data_entry_id", "data_entry_id_describe",
                                "data_entry_id_poci","data_entry_id_wabr_base",
                                "data_entry_id_scenario_base","data_entry_id_ghq12_base",
                                "data_entry_id_saqol_base","data_entry_id_ipraise",
                                "data_entry_id_therapy","data_entry_id_anchorlang",
                                "data_entry_id_anchorlangpt","data_entry_id_wabr_post",
                                "data_entry_id_anchorcom","data_entry_id_anchorcompt",
                                "data_entry_id_scenario_post","data_entry_id_anchorewb",
                                "data_entry_id_anchorewbpt","data_entry_id_ghq12_post",
                                "data_entry_id_anchorqol","data_entry_id_anchorqolpt",
                                "data_entry_id_saqol_post","data_entry_id_ptex",
                                "data_entry_id_dc","data_entry_id_end","end_of_study_complete")

# Count the number of instruments each clinician has entered data into
clin_dt <- clinicians  %>% 
  pivot_longer(cols = starts_with("data_entry"), names_to = "role", values_to = "clinician") %>%
  filter(clinician != "[survey respondent]") %>%
  filter(clinician != "rrr_samh") %>%
  group_by(clinician, participant_id, end_of_study_complete) %>%
  summarise(count = n(), .groups = 'drop') %>% filter(clinician != '')


# Calculate the number of unique participants each clinician has seen
unique_participants <- clin_dt %>%
  group_by(clinician) %>%
  summarise(unique_participants = n_distinct(participant_id))%>%
  arrange(desc(unique_participants))  # Order by highest to lowest

# Calculate the number of unique completed participants each clinician has seen
unique_comp_participants <- clin_dt %>%
  group_by(clinician) %>%
  filter(end_of_study_complete == 2) %>%
  summarise(unique_comp_participants = n_distinct(participant_id))%>%
  arrange(desc(unique_comp_participants))  # Order by highest to lowest

# Calculate total number of instruments completed by each clinician
total_instruments <- clin_dt %>% 
  group_by(clinician) %>%
  summarise(total_instruments = sum(count, na.rm = TRUE)) 

# Merge these dataframes

# Merge the first two tables: unique_participants and unique_comp_participants
merged_clin_data <- left_join(unique_participants, unique_comp_participants, by = "clinician")

# Merge the result with the total_instruments table
merged_clin_data <- left_join(merged_clin_data, total_instruments, by = "clinician") %>%
  arrange(desc(unique_participants))

# Replace NA with 0 in the entire dataframe
merged_clin_data[is.na(merged_clin_data)] <- 0

# Rename the columns
merged_clin_data <- merged_clin_data %>%
  rename(
    Clinician = clinician,
    `Unique Participants` = unique_participants,
    `Completed Participants` = unique_comp_participants,
    `# of instruments` = total_instruments
  )

# Display the merged data frame as an HTML table, centred and narrow
#knitr::kable(merged_clin_data, format = "html", 
             #table.attr = "class='table table-striped' style='width:50%; margin-left:auto; margin-right:auto;'")

datatable(merged_clin_data, caption = paste("Last updated: ",format(Sys.Date(), "%d-%m-%Y")), 
          rownames=FALSE,extensions = "Buttons",
          options = list(initComplete = JS("function(settings, json) {",
    "$(this.api().table().header()).css({'background-color': '#fff', 'color': '#000'});","}"),
    columnDefs =list(list(className = 'dt-center', targets="_all"), 
                     list(width = '100px', targets = 0),
                     list(width = '50px', targets = 1),
                     list(width = '50px', targets = 2),
                     list(width = '50px', targets = 3)), 
                     pageLength =25 ,dom = 'lfrtBip', buttons = c('csv', 'excel', 'pdf'), 
                     lengthMenu =list(c(25,50,100,-1), c("25","50","100","ALL")) ,autoWidth = FALSE, compact = TRUE),
  class = "compact stripe hover row-border order-column") 

```
